# Generated by Django 5.2.17 on 2026-09-08 21:45

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(blank=True, max_length=60, verbose_name='SKU')),
                ('description', models.TextField(blank=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_on_hand', models.PositiveIntegerField(default=0, editable=False)),
                ('low_stock_threshold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='businesses.business')),
            ],
            options={
                'ordering': ('name', 'pk'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('business'), name='unique_product_name_per_business'), models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), models.F('business'), condition=models.Q(('sku', ''), _negated=True), name='unique_nonempty_sku_per_business'), models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='nonnegative_selling_price'), models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='nonnegative_unit_cost'), models.CheckConstraint(condition=models.Q(('stock_on_hand__gte', 0)), name='nonnegative_stock_on_hand'), models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='nonnegative_low_stock_threshold')],
            },
        ),
    ]
