# Generated by Django 5.2.17 on 2026-09-09 10:10

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement', to='purchases.purchaseline'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('adjustment', 'Stock Adjustment'), ('purchase', 'Purchase')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_adjustment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement', to='inventory.stockadjustment'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(
                condition=(
                    Q(
                        ('kind', 'adjustment'),
                        ('purchase_line__isnull', True),
                        ('stock_adjustment__isnull', False),
                    )
                    | Q(
                        ('kind', 'purchase'),
                        ('purchase_line__isnull', False),
                        ('stock_adjustment__isnull', True),
                    )
                ),
                name='stock_movement_has_matching_origin',
            ),
        ),
    ]
