# Generated by Django 5.2.17 on 2026-09-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_purchase_line_alter_stockmovement_kind_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='stock_movement_has_matching_origin',
        ),
    ]
