# Generated by Django 5.2.17 on 2026-09-09 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('inventory', '0003_remove_stockmovement_stock_movement_has_matching_origin'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='sale_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement', to='sales.saleline'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('adjustment', 'Stock Adjustment'), ('purchase', 'Purchase'), ('sale', 'Sale')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'adjustment'), ('purchase_line__isnull', True), ('sale_line__isnull', True), ('stock_adjustment__isnull', False)), models.Q(('kind', 'purchase'), ('purchase_line__isnull', False), ('sale_line__isnull', True), ('stock_adjustment__isnull', True)), models.Q(('kind', 'sale'), ('purchase_line__isnull', True), ('sale_line__isnull', False), ('stock_adjustment__isnull', True)), _connector='OR'), name='stock_movement_has_matching_origin'),
        ),
    ]
