# Generated by Django 5.2.17 on 2026-09-11 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('inventory', '0004_stockmovement_sale_line_alter_stockmovement_kind_and_more'),
        ('purchases', '0002_alter_purchase_status'),
        ('sales', '0002_alter_sale_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='stock_movement_has_matching_origin',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='inventory.stockmovement'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('adjustment', 'Stock Adjustment'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('reversal', 'Reversal')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'adjustment'), ('purchase_line__isnull', True), ('reversal_of__isnull', True), ('sale_line__isnull', True), ('stock_adjustment__isnull', False)), models.Q(('kind', 'purchase'), ('purchase_line__isnull', False), ('reversal_of__isnull', True), ('sale_line__isnull', True), ('stock_adjustment__isnull', True)), models.Q(('kind', 'sale'), ('purchase_line__isnull', True), ('reversal_of__isnull', True), ('sale_line__isnull', False), ('stock_adjustment__isnull', True)), models.Q(('kind', 'reversal'), ('purchase_line__isnull', True), ('reversal_of__isnull', False), ('sale_line__isnull', True), ('stock_adjustment__isnull', True)), _connector='OR'), name='stock_movement_has_matching_origin'),
        ),
    ]
